GET http://localhost:3000/users

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "name" : "Russell",
    "surname" : "Johnson",
    "username" : "blueyorange",
    "email" : "blueyorange@gmail.com",
    "dateOfBirth" : "1980-06-28",
    "password" : "yaypassword"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "blueyorange",
    "password" : "password"
}

###
GET http://localhost:3000/

###