GET http://localhost:3000/users

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "firstname" : "Russell",
    "surname" : "Johnson",
    "username" : "pooeyorange",
    "email" : "pooeyorange@gmail.com",
    "password" : "wowPassword%6"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "blueyorange",
    "password" : "password"
}

###
GET http://localhost:3000/

###